services:
  dashboard-client:
    image: dashboard-client
    container_name: dashboard-client
    build:
      context: ./client
    volumes:
      - ./client:/app:rw
      - node_modules:/app/node_modules
    networks:
      - client-side
    ports:
      - 8000:8000

volumes:
  node_modules:

networks:
  client-side: {}
